[package]
name = "pgvector"
version = "0.2.2"
description = "pgvector support for Rust"
repository = "https://github.com/pgvector/pgvector-rust"
license = "MIT OR Apache-2.0"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2018"
readme = "README.md"

[dependencies]
byteorder = "1"
bytes = "1"
postgres = { version = "0", optional = true }
diesel = { version = "2", features = ["postgres"], optional = true }
sqlx = { git = "https://github.com/launchbadge/sqlx", features = ["postgres"], optional = true }

[dev-dependencies]
sqlx = { git = "https://github.com/launchbadge/sqlx", features = ["runtime-async-std-native-tls"] }
async-std = { version = "1", features = ["attributes"] }

[features]
default = ["postgres"]
